name: nip44
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  elliptic: ^0.3.11
  cryptography: ^2.7.0
  collection: ^1.19.1
  crypto: ^3.0.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
